// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WepApiBookSamsys.Infrastructure.Entities;

#nullable disable

namespace WebApiBookSamsys.Migrations
{
    [DbContext(typeof(BookSamsysContext))]
    [Migration("20231117192404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WepApiBookSamsys.Infrastructure.Entities.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar (50)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("WepApiBookSamsys.Infrastructure.Entities.Livro", b =>
                {
                    b.Property<int>("ISBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ISBN"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar (50)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ISBN");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("WepApiBookSamsys.Infrastructure.Entities.Livro_autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorIdAutor")
                        .HasColumnType("int");

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<int?>("LivroISBN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorIdAutor");

                    b.HasIndex("LivroISBN");

                    b.ToTable("Livro_Autores");
                });

            modelBuilder.Entity("WepApiBookSamsys.Infrastructure.Entities.Livro_autor", b =>
                {
                    b.HasOne("WepApiBookSamsys.Infrastructure.Entities.Autor", null)
                        .WithMany("Livro_autores")
                        .HasForeignKey("AutorIdAutor");

                    b.HasOne("WepApiBookSamsys.Infrastructure.Entities.Livro", null)
                        .WithMany("livro_Autors")
                        .HasForeignKey("LivroISBN");
                });

            modelBuilder.Entity("WepApiBookSamsys.Infrastructure.Entities.Autor", b =>
                {
                    b.Navigation("Livro_autores");
                });

            modelBuilder.Entity("WepApiBookSamsys.Infrastructure.Entities.Livro", b =>
                {
                    b.Navigation("livro_Autors");
                });
#pragma warning restore 612, 618
        }
    }
}
